"""Agent memory system — short-term, long-term, and relationships."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class MemoryEntry:
    """A single memory entry."""

    tick: int
    content: str
    importance: float = 0.5  # 0.0 to 1.0
    timestamp: datetime | None = None
    related_agents: list[str] = field(default_factory=list)

    def __str__(self) -> str:
        return f"[tick {self.tick}] {self.content}"


@dataclass
class Relationship:
    """Tracks relationship between two agents."""

    agent_name: str
    sentiment: float = 0.0  # -1.0 (hostile) to 1.0 (close friend)
    interactions: int = 0
    last_interaction_tick: int = 0
    notes: list[str] = field(default_factory=list)

    def describe(self) -> str:
        if self.sentiment > 0.5:
            tone = "close friend"
        elif self.sentiment > 0.1:
            tone = "friendly acquaintance"
        elif self.sentiment > -0.1:
            tone = "neutral"
        elif self.sentiment > -0.5:
            tone = "unfriendly"
        else:
            tone = "hostile"
        return f"{self.agent_name} ({tone}, {self.interactions} interactions)"


class MemorySystem:
    """Manages an agent's short-term and long-term memory."""

    def __init__(self, short_term_limit: int = 20, long_term_limit: int = 50):
        self.short_term: list[MemoryEntry] = []
        self.long_term: list[MemoryEntry] = []
        self.relationships: dict[str, Relationship] = {}
        self.short_term_limit = short_term_limit
        self.long_term_limit = long_term_limit
        self._reflection_summaries: list[str] = []

    def add(self, tick: int, content: str, importance: float = 0.5,
            related_agents: list[str] | None = None) -> MemoryEntry:
        """Add a new memory to short-term storage."""
        entry = MemoryEntry(
            tick=tick,
            content=content,
            importance=importance,
            related_agents=related_agents or [],
        )
        self.short_term.append(entry)

        # Promote high-importance memories directly to long-term
        if importance >= 0.8:
            self.long_term.append(entry)
            if len(self.long_term) > self.long_term_limit:
                # Remove least important long-term memory
                self.long_term.sort(key=lambda m: m.importance)
                self.long_term.pop(0)

        # Trim short-term if over limit
        if len(self.short_term) > self.short_term_limit:
            self.short_term.pop(0)

        return entry

    def update_relationship(self, agent_name: str, sentiment_delta: float,
                            tick: int, note: str = "") -> Relationship:
        """Update or create a relationship with another agent."""
        if agent_name not in self.relationships:
            self.relationships[agent_name] = Relationship(agent_name=agent_name)

        rel = self.relationships[agent_name]
        rel.sentiment = max(-1.0, min(1.0, rel.sentiment + sentiment_delta))
        rel.interactions += 1
        rel.last_interaction_tick = tick
        if note:
            rel.notes.append(note)
            if len(rel.notes) > 10:
                rel.notes.pop(0)
        return rel

    def add_reflection(self, summary: str) -> None:
        """Add a reflection summary (generated by LLM periodically)."""
        self._reflection_summaries.append(summary)
        if len(self._reflection_summaries) > 20:
            self._reflection_summaries.pop(0)

    def get_context(self, max_entries: int = 15) -> str:
        """Build a memory context string for LLM prompts."""
        parts = []

        # Recent memories
        recent = self.short_term[-max_entries:]
        if recent:
            parts.append("Recent events:")
            for m in recent:
                parts.append(f"  - {m}")

        # Key long-term memories
        important = sorted(self.long_term, key=lambda m: m.importance, reverse=True)[:5]
        if important:
            parts.append("\nImportant memories:")
            for m in important:
                parts.append(f"  - {m}")

        # Relationships
        if self.relationships:
            parts.append("\nRelationships:")
            for rel in self.relationships.values():
                parts.append(f"  - {rel.describe()}")

        # Reflections
        if self._reflection_summaries:
            parts.append("\nReflections:")
            for s in self._reflection_summaries[-3:]:
                parts.append(f"  - {s}")

        return "\n".join(parts)

    def get_relationship(self, agent_name: str) -> Relationship | None:
        return self.relationships.get(agent_name)
